-- MarketLab V1 optional shared leaderboard table.
-- Run this in the Supabase SQL Editor, then add SUPABASE_URL and
-- SUPABASE_SERVICE_ROLE_KEY to Render. The browser never receives the service key.

create table if not exists public.class_participants (
  id bigint generated by default as identity primary key,
  player_id text not null,
  class_code text not null,
  display_name text not null,
  portfolio_value numeric not null default 100000,
  cash_balance numeric not null default 100000,
  return_percent numeric not null default 0,
  holdings_count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (class_code, player_id)
);

create index if not exists class_participants_class_code_idx
  on public.class_participants (class_code, portfolio_value desc);

alter table public.class_participants enable row level security;

-- No anon/authenticated policies are intentionally added in V1.
-- The Next.js server accesses this table with the service role key only.
